import dynamic from "next/dynamic"
import { createDefaultCustomization } from "@/lib/resume/factory"
import type { TemplateDefinition } from "@/types/template"
import type { TemplateId } from "@/types/resume"

function customization(overrides: Partial<ReturnType<typeof createDefaultCustomization>> = {}) {
  return { ...createDefaultCustomization(), ...overrides }
}

export const TEMPLATE_REGISTRY: Record<TemplateId, TemplateDefinition> = {
  "modern-ats": {
    id: "modern-ats",
    name: "Modern ATS",
    description: "Black & white, single column, built to sail through applicant tracking systems.",
    categories: ["ATS Friendly", "Freshers", "Corporate"],
    hasPhoto: false,
    badges: ["ats", "popular"],
    defaultCustomization: customization({ primaryColor: "#111827", accentColor: "#111827", headingStyle: "uppercase" }),
    PreviewComponent: dynamic(() => import("@/components/templates/modern-ats/Preview").then((m) => m.ModernAtsPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ModernAtsDocument").then((m) => m.ModernAtsDocument),
  },
  "professional-blue": {
    id: "professional-blue",
    name: "Professional Blue",
    description: "Two-column sidebar layout with a bold blue rail for contact details and skills.",
    categories: ["Corporate", "Experienced"],
    hasPhoto: false,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#1d4ed8", accentColor: "#1d4ed8" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/professional-blue/Preview").then((m) => m.ProfessionalBluePreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/ProfessionalBlueDocument").then((m) => m.ProfessionalBlueDocument),
  },
  "minimal-elegant": {
    id: "minimal-elegant",
    name: "Minimal Elegant",
    description: "Quiet, whitespace-forward single column with a light touch of typographic elegance.",
    categories: ["Minimal", "Students"],
    hasPhoto: false,
    badges: ["ats"],
    defaultCustomization: customization({ primaryColor: "#334155", accentColor: "#64748b", headingStyle: "minimal" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/minimal-elegant/Preview").then((m) => m.MinimalElegantPreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/MinimalElegantDocument").then((m) => m.MinimalElegantDocument),
  },
  "corporate-executive": {
    id: "corporate-executive",
    name: "Corporate Executive",
    description: "Formal photo header for senior and leadership roles, with a structured single column body.",
    categories: ["Executives", "Corporate"],
    hasPhoto: true,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1e3a5f", accentColor: "#b45309", headingStyle: "boxed" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/corporate-executive/Preview").then((m) => m.CorporateExecutivePreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/CorporateExecutiveDocument").then((m) => m.CorporateExecutiveDocument),
  },
  "creative-designer": {
    id: "creative-designer",
    name: "Creative Designer",
    description: "Bold color-blocked header with photo and a vivid accent sidebar for design portfolios.",
    categories: ["Designers", "Creative"],
    hasPhoto: true,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#7c3aed", accentColor: "#f59e0b" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/creative-designer/Preview").then((m) => m.CreativeDesignerPreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/CreativeDesignerDocument").then((m) => m.CreativeDesignerDocument),
  },
  "material-style": {
    id: "material-style",
    name: "Material Style",
    description: "Elevated cards per section with Material-Design-inspired color and shadow.",
    categories: ["Software Engineers", "Designers"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#0f766e", accentColor: "#0ea5e9", fontFamily: "roboto" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/material-style/Preview").then((m) => m.MaterialStylePreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/MaterialStyleDocument").then((m) => m.MaterialStyleDocument),
  },
  "classic-resume": {
    id: "classic-resume",
    name: "Classic Resume",
    description: "Traditional centered header with full-width section rules — timeless and dependable.",
    categories: ["Corporate", "Experienced"],
    hasPhoto: false,
    badges: ["ats"],
    defaultCustomization: customization({ primaryColor: "#111827", accentColor: "#111827", fontFamily: "merriweather" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/classic-resume/Preview").then((m) => m.ClassicResumePreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/ClassicResumeDocument").then((m) => m.ClassicResumeDocument),
  },
  "modern-green": {
    id: "modern-green",
    name: "Modern Green",
    description: "Clean single column with a fresh green accent rule under every heading.",
    categories: ["Software Engineers", "Freshers"],
    hasPhoto: false,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#15803d", accentColor: "#15803d" }),
    PreviewComponent: dynamic(() => import("@/components/templates/modern-green/Preview").then((m) => m.ModernGreenPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ModernGreenDocument").then((m) => m.ModernGreenDocument),
  },
  "elegant-purple": {
    id: "elegant-purple",
    name: "Elegant Purple",
    description: "Soft banner header with an airy two-column body split between story and specifics.",
    categories: ["Creative", "Students"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#7c3aed", accentColor: "#a855f7" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/elegant-purple/Preview").then((m) => m.ElegantPurplePreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/ElegantPurpleDocument").then((m) => m.ElegantPurpleDocument),
  },
  "premium-portfolio": {
    id: "premium-portfolio",
    name: "Premium Portfolio",
    description: "The flagship template: a refined dark sidebar with photo, dividers, and structured columns.",
    categories: ["Executives", "Designers"],
    hasPhoto: true,
    badges: ["premium", "popular"],
    defaultCustomization: customization({ primaryColor: "#111827", accentColor: "#d4a373", headingStyle: "underline" }),
    PreviewComponent: dynamic(() =>
      import("@/components/templates/premium-portfolio/Preview").then((m) => m.PremiumPortfolioPreview)
    ),
    loadPdfDocument: () => import("@/components/pdf/documents/PremiumPortfolioDocument").then((m) => m.PremiumPortfolioDocument),
  },
  "timeline-classic": {
    id: "timeline-classic",
    name: "Timeline Classic",
    description: "Left-aligned header with a quiet dotted timeline running down every section — dependable and easy to scan.",
    categories: ["Experienced", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1e3a5f", accentColor: "#64748b", fontFamily: "merriweather", headingStyle: "underline", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/timeline-classic/Preview").then((m) => m.TimelineClassicPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/TimelineClassicDocument").then((m) => m.TimelineClassicDocument),
  },
  "timeline-vivid": {
    id: "timeline-vivid",
    name: "Timeline Vivid",
    description: "Bold dotted timeline in a vivid teal-orange palette, built for engineers and builders who want personality without clutter.",
    categories: ["Software Engineers", "Creative"],
    hasPhoto: false,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#0f766e", accentColor: "#f97316", fontFamily: "poppins", headingStyle: "bold", iconStyle: "filled" }),
    PreviewComponent: dynamic(() => import("@/components/templates/timeline-vivid/Preview").then((m) => m.TimelineVividPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/TimelineVividDocument").then((m) => m.TimelineVividDocument),
  },
  "timeline-monochrome": {
    id: "timeline-monochrome",
    name: "Timeline Mono",
    description: "Pure black-and-white timeline layout, stripped of color for maximum ATS compatibility.",
    categories: ["ATS Friendly", "Freshers"],
    hasPhoto: false,
    badges: ["ats"],
    defaultCustomization: customization({ primaryColor: "#111827", accentColor: "#111827", fontFamily: "inter", headingStyle: "uppercase", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/timeline-monochrome/Preview").then((m) => m.TimelineMonoPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/TimelineMonoDocument").then((m) => m.TimelineMonoDocument),
  },
  "timeline-dark": {
    id: "timeline-dark",
    name: "Timeline Navy",
    description: "A filled navy header banner leads into a clean dotted timeline body — polished for senior candidates.",
    categories: ["Executives", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1e293b", accentColor: "#d4a373", fontFamily: "montserrat", headingStyle: "boxed", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/timeline-dark/Preview").then((m) => m.TimelineNavyPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/TimelineNavyDocument").then((m) => m.TimelineNavyDocument),
  },
  "right-rail-slate": {
    id: "right-rail-slate",
    name: "Right Rail Slate",
    description: "Clean left-aligned body with a solid slate sidebar on the right for skills and extras.",
    categories: ["Corporate", "Experienced"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#334155", accentColor: "#0ea5e9", fontFamily: "inter", headingStyle: "minimal", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/right-rail-slate/Preview").then((m) => m.RightRailSlatePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/RightRailSlateDocument").then((m) => m.RightRailSlateDocument),
  },
  "right-rail-emerald": {
    id: "right-rail-emerald",
    name: "Right Rail Emerald",
    description: "The same trusted sidebar layout in a fresh emerald tone, popular with product and ops roles.",
    categories: ["Experienced", "Software Engineers"],
    hasPhoto: false,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#047857", accentColor: "#10b981", fontFamily: "lato", headingStyle: "bold", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/right-rail-emerald/Preview").then((m) => m.RightRailEmeraldPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/RightRailEmeraldDocument").then((m) => m.RightRailEmeraldDocument),
  },
  "right-rail-crimson": {
    id: "right-rail-crimson",
    name: "Right Rail Crimson",
    description: "A confident crimson sidebar layout that keeps the main narrative on the left where recruiters look first.",
    categories: ["Corporate", "Executives"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#9f1239", accentColor: "#e11d48", fontFamily: "montserrat", headingStyle: "uppercase", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/right-rail-crimson/Preview").then((m) => m.RightRailCrimsonPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/RightRailCrimsonDocument").then((m) => m.RightRailCrimsonDocument),
  },
  "right-rail-graphite": {
    id: "right-rail-graphite",
    name: "Right Rail Graphite",
    description: "Graphite sidebar with a gold accent — a refined, premium-feeling take on the sidebar resume.",
    categories: ["Executives", "Designers"],
    hasPhoto: false,
    badges: ["premium"],
    defaultCustomization: customization({ primaryColor: "#1f2937", accentColor: "#d4a373", fontFamily: "roboto", headingStyle: "boxed", iconStyle: "filled" }),
    PreviewComponent: dynamic(() => import("@/components/templates/right-rail-graphite/Preview").then((m) => m.RightRailGraphitePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/RightRailGraphiteDocument").then((m) => m.RightRailGraphiteDocument),
  },
  "duotone-blue-amber": {
    id: "duotone-blue-amber",
    name: "Duotone Blue",
    description: "A vertical two-tone header block in blue and amber frames your photo, then settles into a clean single column.",
    categories: ["Creative", "Designers"],
    hasPhoto: true,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#1d4ed8", accentColor: "#f59e0b", fontFamily: "poppins", headingStyle: "bold", iconStyle: "filled" }),
    PreviewComponent: dynamic(() => import("@/components/templates/duotone-blue-amber/Preview").then((m) => m.DuotoneBluePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/DuotoneBlueDocument").then((m) => m.DuotoneBlueDocument),
  },
  "duotone-plum-rose": {
    id: "duotone-plum-rose",
    name: "Duotone Plum",
    description: "A diagonal plum-and-rose header split gives this template a distinct, gallery-ready silhouette.",
    categories: ["Creative", "Designers"],
    hasPhoto: true,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#6b21a8", accentColor: "#fb7185", fontFamily: "poppins", headingStyle: "bold", iconStyle: "filled" }),
    PreviewComponent: dynamic(() => import("@/components/templates/duotone-plum-rose/Preview").then((m) => m.DuotonePlumPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/DuotonePlumDocument").then((m) => m.DuotonePlumDocument),
  },
  "duotone-forest-lime": {
    id: "duotone-forest-lime",
    name: "Duotone Forest",
    description: "Earthy forest-and-lime two-tone header, vertical split, for outdoorsy and sustainability-minded brands.",
    categories: ["Creative", "Software Engineers"],
    hasPhoto: true,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#14532d", accentColor: "#84cc16", fontFamily: "montserrat", headingStyle: "underline", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/duotone-forest-lime/Preview").then((m) => m.DuotoneForestPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/DuotoneForestDocument").then((m) => m.DuotoneForestDocument),
  },
  "duotone-navy-gold": {
    id: "duotone-navy-gold",
    name: "Duotone Gold",
    description: "A diagonal navy-and-gold header split reads premium and formal without losing the creative split-header idea.",
    categories: ["Executives", "Creative"],
    hasPhoto: true,
    badges: ["premium"],
    defaultCustomization: customization({ primaryColor: "#1e293b", accentColor: "#d4a373", fontFamily: "merriweather", headingStyle: "underline", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/duotone-navy-gold/Preview").then((m) => m.DuotoneGoldPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/DuotoneGoldDocument").then((m) => m.DuotoneGoldDocument),
  },
  "compact-ats": {
    id: "compact-ats",
    name: "Compact ATS",
    description: "Every pixel earns its keep — a dense, black-and-white single column built to fit more on one page.",
    categories: ["ATS Friendly", "Freshers"],
    hasPhoto: false,
    badges: ["ats"],
    defaultCustomization: customization({ primaryColor: "#111827", accentColor: "#111827", fontFamily: "inter", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/compact-ats/Preview").then((m) => m.CompactAtsPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/CompactAtsDocument").then((m) => m.CompactAtsDocument),
  },
  "compact-serif": {
    id: "compact-serif",
    name: "Compact Serif",
    description: "A dense serif single column that fits a full career story on one page without feeling cramped.",
    categories: ["Experienced", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1f2937", accentColor: "#78716c", fontFamily: "merriweather", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/compact-serif/Preview").then((m) => m.CompactSerifPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/CompactSerifDocument").then((m) => m.CompactSerifDocument),
  },
  "compact-mono": {
    id: "compact-mono",
    name: "Compact Sharp",
    description: "Tight, structured spacing with crisp uppercase labels — a sharp, no-nonsense one-pager.",
    categories: ["Software Engineers", "ATS Friendly"],
    hasPhoto: false,
    badges: ["ats"],
    defaultCustomization: customization({ primaryColor: "#0f172a", accentColor: "#0ea5e9", fontFamily: "roboto", headingStyle: "minimal", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/compact-mono/Preview").then((m) => m.CompactSharpPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/CompactSharpDocument").then((m) => m.CompactSharpDocument),
  },
  "compact-color": {
    id: "compact-color",
    name: "Compact Color",
    description: "The same space-efficient dense layout with a warm accent underline for a touch of personality.",
    categories: ["Freshers", "Students"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#b45309", accentColor: "#f59e0b", fontFamily: "lato", headingStyle: "underline", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/compact-color/Preview").then((m) => m.CompactColorPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/CompactColorDocument").then((m) => m.CompactColorDocument),
  },
  "scholar-classic": {
    id: "scholar-classic",
    name: "Scholar Classic",
    description: "A formal, centered academic layout with generous line-height — well suited to research and teaching CVs.",
    categories: ["Students", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1f2937", accentColor: "#6b7280", fontFamily: "merriweather", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/scholar-classic/Preview").then((m) => m.ScholarClassicPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ScholarClassicDocument").then((m) => m.ScholarClassicDocument),
  },
  "scholar-modern": {
    id: "scholar-modern",
    name: "Scholar Modern",
    description: "The same academic structure in a contemporary sans-serif, for candidates who want formal without feeling old-fashioned.",
    categories: ["Students", "Experienced"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1e3a5f", accentColor: "#64748b", fontFamily: "open-sans", headingStyle: "minimal", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/scholar-modern/Preview").then((m) => m.ScholarModernPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ScholarModernDocument").then((m) => m.ScholarModernDocument),
  },
  "scholar-ivy": {
    id: "scholar-ivy",
    name: "Scholar Ivy",
    description: "A deep burgundy accent brings quiet prestige to this traditional academic-style resume.",
    categories: ["Corporate", "Executives"],
    hasPhoto: false,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#7f1d1d", accentColor: "#b91c1c", fontFamily: "merriweather", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/scholar-ivy/Preview").then((m) => m.ScholarIvyPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ScholarIvyDocument").then((m) => m.ScholarIvyDocument),
  },
  "scholar-research": {
    id: "scholar-research",
    name: "Scholar Research",
    description: "Forest-and-gold detailing on a formal research-CV structure that surfaces publications and certifications first.",
    categories: ["Students", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#14532d", accentColor: "#b45309", fontFamily: "merriweather", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/scholar-research/Preview").then((m) => m.ScholarResearchPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ScholarResearchDocument").then((m) => m.ScholarResearchDocument),
  },
  "framed-classic": {
    id: "framed-classic",
    name: "Framed Classic",
    description: "A crisp hairline frame around the page gives this traditional layout a printed, letterhead feel.",
    categories: ["Corporate", "Experienced"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#111827", accentColor: "#111827", fontFamily: "merriweather", headingStyle: "underline", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/framed-classic/Preview").then((m) => m.FramedClassicPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/FramedClassicDocument").then((m) => m.FramedClassicDocument),
  },
  "framed-elegant": {
    id: "framed-elegant",
    name: "Framed Elegant",
    description: "A soft mauve frame and airy spacing make this a graceful choice for client-facing and design roles.",
    categories: ["Designers", "Creative"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#6b21a8", accentColor: "#a855f7", fontFamily: "lato", headingStyle: "underline", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/framed-elegant/Preview").then((m) => m.FramedElegantPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/FramedElegantDocument").then((m) => m.FramedElegantDocument),
  },
  "framed-bold": {
    id: "framed-bold",
    name: "Framed Bold",
    description: "A thick double-ruled frame and bold headings make a confident, attention-holding first impression.",
    categories: ["Executives", "Corporate"],
    hasPhoto: false,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#1e293b", accentColor: "#d97706", fontFamily: "montserrat", headingStyle: "bold", iconStyle: "filled" }),
    PreviewComponent: dynamic(() => import("@/components/templates/framed-bold/Preview").then((m) => m.FramedBoldPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/FramedBoldDocument").then((m) => m.FramedBoldDocument),
  },
  "framed-minimal": {
    id: "framed-minimal",
    name: "Framed Minimal",
    description: "The lightest possible frame around a quiet, whitespace-forward layout for understated resumes.",
    categories: ["Minimal", "Students"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#334155", accentColor: "#94a3b8", fontFamily: "inter", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/framed-minimal/Preview").then((m) => m.FramedMinimalPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/FramedMinimalDocument").then((m) => m.FramedMinimalDocument),
  },
  "chip-teal": {
    id: "chip-teal",
    name: "Chip Teal",
    description: "Skills and languages render as tidy rounded chips in a light sidebar, easy for recruiters to scan at a glance.",
    categories: ["Software Engineers", "Designers"],
    hasPhoto: false,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#0f766e", accentColor: "#14b8a6", fontFamily: "inter", headingStyle: "bold", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/chip-teal/Preview").then((m) => m.ChipTealPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ChipTealDocument").then((m) => m.ChipTealDocument),
  },
  "chip-indigo": {
    id: "chip-indigo",
    name: "Chip Indigo",
    description: "The same scannable chip-based skills sidebar in a rich indigo palette.",
    categories: ["Software Engineers", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#4338ca", accentColor: "#6366f1", fontFamily: "poppins", headingStyle: "bold", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/chip-indigo/Preview").then((m) => m.ChipIndigoPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ChipIndigoDocument").then((m) => m.ChipIndigoDocument),
  },
  "chip-coral": {
    id: "chip-coral",
    name: "Chip Coral",
    description: "A lively coral chip sidebar brings warmth to a structured two-column layout.",
    categories: ["Creative", "Freshers"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#c2410c", accentColor: "#fb923c", fontFamily: "lato", headingStyle: "bold", iconStyle: "filled" }),
    PreviewComponent: dynamic(() => import("@/components/templates/chip-coral/Preview").then((m) => m.ChipCoralPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ChipCoralDocument").then((m) => m.ChipCoralDocument),
  },
  "chip-olive": {
    id: "chip-olive",
    name: "Chip Olive",
    description: "An earthy olive chip sidebar for a grounded, understated professional look.",
    categories: ["Experienced", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#3f6212", accentColor: "#84cc16", fontFamily: "roboto", headingStyle: "bold", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/chip-olive/Preview").then((m) => m.ChipOlivePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/ChipOliveDocument").then((m) => m.ChipOliveDocument),
  },
  "portrait-clean": {
    id: "portrait-clean",
    name: "Portrait Clean",
    description: "A centered circular photo and calm sky-blue accent line keep the focus on a clean, friendly header.",
    categories: ["Freshers", "Students"],
    hasPhoto: true,
    badges: ["popular"],
    defaultCustomization: customization({ primaryColor: "#0369a1", accentColor: "#38bdf8", fontFamily: "inter", headingStyle: "minimal", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/portrait-clean/Preview").then((m) => m.PortraitCleanPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/PortraitCleanDocument").then((m) => m.PortraitCleanDocument),
  },
  "portrait-bold": {
    id: "portrait-bold",
    name: "Portrait Bold",
    description: "A bold color block frames the centered photo for a striking, magazine-style header.",
    categories: ["Creative", "Designers"],
    hasPhoto: true,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#be185d", accentColor: "#f97316", fontFamily: "poppins", headingStyle: "bold", iconStyle: "filled" }),
    PreviewComponent: dynamic(() => import("@/components/templates/portrait-bold/Preview").then((m) => m.PortraitBoldPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/PortraitBoldDocument").then((m) => m.PortraitBoldDocument),
  },
  "portrait-soft": {
    id: "portrait-soft",
    name: "Portrait Soft",
    description: "A softly tinted header wraps the centered photo in a warm, approachable palette.",
    categories: ["Students", "Creative"],
    hasPhoto: true,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#7c3aed", accentColor: "#c4b5fd", fontFamily: "lato", headingStyle: "underline", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/portrait-soft/Preview").then((m) => m.PortraitSoftPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/PortraitSoftDocument").then((m) => m.PortraitSoftDocument),
  },
  "portrait-dark": {
    id: "portrait-dark",
    name: "Portrait Dark",
    description: "A filled dark header with a bright photo ring gives this centered-portrait layout an executive edge.",
    categories: ["Executives", "Corporate"],
    hasPhoto: true,
    badges: ["premium"],
    defaultCustomization: customization({ primaryColor: "#111827", accentColor: "#d4a373", fontFamily: "montserrat", headingStyle: "boxed", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/portrait-dark/Preview").then((m) => m.PortraitDarkPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/PortraitDarkDocument").then((m) => m.PortraitDarkDocument),
  },
  "grid-header-blue": {
    id: "grid-header-blue",
    name: "Grid Header Blue",
    description: "Contact details align into a tidy two-column grid beneath the name, for an organized, structured first impression.",
    categories: ["Corporate", "Experienced"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1d4ed8", accentColor: "#1d4ed8", fontFamily: "inter", headingStyle: "uppercase", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/grid-header-blue/Preview").then((m) => m.GridHeaderBluePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/GridHeaderBlueDocument").then((m) => m.GridHeaderBlueDocument),
  },
  "grid-header-charcoal": {
    id: "grid-header-charcoal",
    name: "Grid Header Charcoal",
    description: "The same structured contact grid in a neutral charcoal palette, quietly professional.",
    categories: ["ATS Friendly", "Corporate"],
    hasPhoto: false,
    badges: ["ats"],
    defaultCustomization: customization({ primaryColor: "#1f2937", accentColor: "#4b5563", fontFamily: "roboto", headingStyle: "uppercase", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/grid-header-charcoal/Preview").then((m) => m.GridHeaderCharcoalPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/GridHeaderCharcoalDocument").then((m) => m.GridHeaderCharcoalDocument),
  },
  "grid-header-sage": {
    id: "grid-header-sage",
    name: "Grid Header Sage",
    description: "A three-column contact grid in a calm sage tone keeps a busy contact list easy to scan.",
    categories: ["Experienced", "Minimal"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#3f6212", accentColor: "#65a30d", fontFamily: "open-sans", headingStyle: "minimal", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/grid-header-sage/Preview").then((m) => m.GridHeaderSagePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/GridHeaderSageDocument").then((m) => m.GridHeaderSageDocument),
  },
  "grid-header-rose": {
    id: "grid-header-rose",
    name: "Grid Header Rose",
    description: "A three-column contact grid with a warm rose accent for a distinctive structured header.",
    categories: ["Creative", "Students"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#9f1239", accentColor: "#fb7185", fontFamily: "poppins", headingStyle: "minimal", iconStyle: "outline" }),
    PreviewComponent: dynamic(() => import("@/components/templates/grid-header-rose/Preview").then((m) => m.GridHeaderRosePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/GridHeaderRoseDocument").then((m) => m.GridHeaderRoseDocument),
  },
  "linework-black": {
    id: "linework-black",
    name: "Linework Black",
    description: "Left-aligned, typography-first layout with hairline rules and no color blocks — as minimal as resumes get.",
    categories: ["Minimal", "ATS Friendly"],
    hasPhoto: false,
    badges: ["ats"],
    defaultCustomization: customization({ primaryColor: "#000000", accentColor: "#000000", fontFamily: "inter", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/linework-black/Preview").then((m) => m.LineworkBlackPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/LineworkBlackDocument").then((m) => m.LineworkBlackDocument),
  },
  "linework-navy": {
    id: "linework-navy",
    name: "Linework Navy",
    description: "A centered variant of the hairline typographic layout with a whisper of navy under the name.",
    categories: ["Minimal", "Corporate"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#1e3a5f", accentColor: "#1e3a5f", fontFamily: "lato", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/linework-navy/Preview").then((m) => m.LineworkNavyPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/LineworkNavyDocument").then((m) => m.LineworkNavyDocument),
  },
  "linework-brown": {
    id: "linework-brown",
    name: "Linework Brown",
    description: "Centered hairline layout with a warm sepia accent line, quiet and considered.",
    categories: ["Minimal", "Students"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#78350f", accentColor: "#78350f", fontFamily: "merriweather", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/linework-brown/Preview").then((m) => m.LineworkBrownPreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/LineworkBrownDocument").then((m) => m.LineworkBrownDocument),
  },
  "linework-slate": {
    id: "linework-slate",
    name: "Linework Slate",
    description: "Left-aligned hairline layout in cool slate, the most understated template in the set.",
    categories: ["Minimal", "Freshers"],
    hasPhoto: false,
    badges: [],
    defaultCustomization: customization({ primaryColor: "#334155", accentColor: "#334155", fontFamily: "inter", headingStyle: "minimal", iconStyle: "none" }),
    PreviewComponent: dynamic(() => import("@/components/templates/linework-slate/Preview").then((m) => m.LineworkSlatePreview)),
    loadPdfDocument: () => import("@/components/pdf/documents/LineworkSlateDocument").then((m) => m.LineworkSlateDocument),
  },
}

export const TEMPLATE_LIST = Object.values(TEMPLATE_REGISTRY)

export function getTemplate(id: TemplateId): TemplateDefinition {
  return TEMPLATE_REGISTRY[id]
}
